// packages/dashboard/src/components/WorkspaceLayout.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { AgentContext, FunctionCategory, CanvasLayout, AnalysisResult, WsMessage } from '@agent-monitor/types';
  import { initFunctions, getFunctionsStore, handleFunctionsMessage, selectFunction } from '$lib/stores/functions.svelte';
  import { initWebSocket, getWebSocketStore } from '$lib/stores/websocket.svelte';
  import { initGitCommits, getGitCommitsStore, selectCommit, clearCommit } from '$lib/stores/gitCommits.svelte';
  import { getCanvasLayoutStore, pinNode, applyCommand, clearLayout } from '$lib/stores/canvasLayout.svelte';
  import { initAnalysis, getAnalysisStore, handleAnalysisMessage, triggerAnalysis, stopAnalysis, getAnalysesForFunction } from '$lib/stores/analysis.svelte';
  import { getGraphScopeStore, computeScope, setFocusMode, setCommitMode, setCategoryMode, clearScope } from '$lib/stores/graphScope.svelte';
  import { WS_URL } from '$lib/constants';
  import { openInEditor, launchDebugSession } from '$lib/api';

  import SidebarTabs from './Sidebar/SidebarTabs.svelte';
  import FileTree from './FileTree/FileTree.svelte';
  import CategoryFilter from './FileTree/CategoryFilter.svelte';
  import FunctionGraph from './Graph/FunctionGraph.svelte';
  import GraphScopeBar from './Graph/GraphScopeBar.svelte';
  import CommitList from './Commits/CommitList.svelte';
  import DiffView from './Commits/DiffView.svelte';
  import DetailPanel from './Detail/DetailPanel.svelte';
  import AgentModal from './Agent/AgentModal.svelte';
  import CanvasAgentPanel from './Agent/CanvasAgentPanel.svelte';
  import SearchPalette from './Search/SearchPalette.svelte';

  const EMPTY_CANVAS_LAYOUT: CanvasLayout = { version: 1, positions: [], groups: [], annotations: [] };

  // Local UI state
  let isDetailOpen = $state(false);
  let isAgentModalOpen = $state(false);
  let agentContext = $state<AgentContext | null>(null);
  let sidebarTab = $state<'files' | 'commits'>('files');
  let selectedCategory = $state<FunctionCategory | null>(null);
  let canvasMode = $state(false);
  let isCanvasAgentOpen = $state(false);
  let isSearchOpen = $state(false);

  // Store accessors
  let fnStore = $derived(getFunctionsStore());
  let wsStore = $derived(getWebSocketStore());
  let gitStore = $derived(getGitCommitsStore());
  let layoutStore = $derived(getCanvasLayoutStore());
  let analysisStore = $derived(getAnalysisStore());
  let scopeStore = $derived(getGraphScopeStore());

  // Derived data
  let { scopedFunctions, scopedEdges } = $derived(computeScope(fnStore.functions, fnStore.edges));

  let filteredFunctions = $derived(
    selectedCategory
      ? fnStore.functions.filter((fn) => fn.category === selectedCategory)
      : fnStore.functions,
  );

  let selectedFunction = $derived(
    fnStore.selectedId
      ? fnStore.functions.find((f) => f.id === fnStore.selectedId) ?? null
      : null,
  );

  let scopedIds = $derived(new Set(scopedFunctions.map((f) => f.id)));

  let analysisMap = $derived.by(() => {
    const map = new Map<string, AnalysisResult[]>();
    for (const a of analysisStore.analyses) {
      if (!scopedIds.has(a.functionId)) continue;
      const existing = map.get(a.functionId);
      if (existing) {
        existing.push(a);
      } else {
        map.set(a.functionId, [a]);
      }
    }
    return map;
  });

  let activeAnalysisRunForSelected = $derived(
    analysisStore.activeRuns.find(
      (r) =>
        (r.status === 'running' || r.status === 'queued') &&
        (fnStore.selectedId && r.functionIds && r.functionIds.includes(fnStore.selectedId)),
    ),
  );

  // Auto-scope tracking
  let prevHighlightedIds: Set<string> = new Set();
  let autoScopeApplied = false;

  $effect(() => {
    const highlighted = gitStore.highlightedFunctionIds;
    if (highlighted !== prevHighlightedIds) {
      prevHighlightedIds = highlighted;
      if (highlighted.size > 0) {
        setCommitMode(highlighted);
      } else if (scopeStore.scopeMode.type === 'commit') {
        clearScope();
      }
    }
  });

  $effect(() => {
    if (selectedCategory) {
      setCategoryMode(new Set([selectedCategory]));
    } else if (scopeStore.scopeMode.type === 'category') {
      clearScope();
    }
  });

  $effect(() => {
    if (autoScopeApplied) return;
    if (fnStore.functions.length <= 300) return;
    if (scopeStore.isScoped) return;
    if (gitStore.commits.length > 0 && gitStore.highlightedFunctionIds.size === 0) {
      selectCommit(gitStore.commits[0].hash, fnStore.functions);
      autoScopeApplied = true;
    }
  });

  // Keyboard shortcut
  function handleKeyDown(e: KeyboardEvent) {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      isSearchOpen = true;
    }
  }

  let cleanupWs: (() => void) | null = null;

  onMount(() => {
    initFunctions();
    initAnalysis();
    initGitCommits();

    cleanupWs = initWebSocket(WS_URL, (msg: WsMessage) => {
      handleFunctionsMessage(msg);
      if (msg.type.startsWith('analysis-')) {
        handleAnalysisMessage(msg);
      }
    });

    window.addEventListener('keydown', handleKeyDown);
  });

  onDestroy(() => {
    cleanupWs?.();
    window.removeEventListener('keydown', handleKeyDown);
  });

  // Handlers
  function handleSelectFunction(id: string) {
    selectFunction(id);
    isDetailOpen = true;
  }

  function handleCloseDetail() {
    isDetailOpen = false;
  }

  function handleAskAgent(ctx: AgentContext) {
    agentContext = ctx;
    isAgentModalOpen = true;
  }

  function handleOpenEditor() {
    if (selectedFunction) {
      openInEditor(selectedFunction.filePath, selectedFunction.line);
    }
  }

  function handleCloseAgent() {
    isAgentModalOpen = false;
  }

  function handleTriggerAnalysis(functionId: string, taskName?: string) {
    triggerAnalysis([functionId], taskName);
  }

  function handleDebugFunction(opts: { filePath: string; line: number; functionName: string }) {
    launchDebugSession(opts);
  }

  function handleDebugCallChain(chain: Array<{ filePath: string; line: number; name: string }>) {
    if (chain.length === 0) return;
    const primary = chain[0];
    launchDebugSession({
      filePath: primary.filePath,
      line: primary.line,
      functionName: primary.name,
      callChain: chain,
    });
  }

  function handleSearchSelect(functionId: string) {
    selectFunction(functionId);
    isDetailOpen = true;
    setFocusMode(functionId);
    isSearchOpen = false;
  }
</script>

<div class="flex flex-col h-screen overflow-hidden bg-void">
  <!-- Top bar -->
  <header class="flex items-center justify-between h-11 px-5 border-b border-border-subtle shrink-0">
    <div class="flex items-center gap-3">
      <div class="flex items-center gap-2">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" class="text-signal">
          <circle cx="7" cy="7" r="5" stroke="currentColor" stroke-width="1.5" />
          <circle cx="7" cy="7" r="2" fill="currentColor" />
        </svg>
        <span class="text-[13px] font-medium tracking-tight text-text">
          vigil
        </span>
      </div>
      <span class="text-text-dim text-[11px]">/</span>
      <span class="text-text-secondary text-[11px]">
        {fnStore.functions.length} function{fnStore.functions.length !== 1 ? 's' : ''} tracked
      </span>
      <button
        onclick={() => canvasMode = !canvasMode}
        class="flex items-center gap-1.5 px-2.5 py-1 text-[11px] rounded transition-colors {canvasMode
          ? 'bg-signal/10 text-signal border border-signal/30'
          : 'text-text-dim border border-border-subtle hover:text-text'}"
      >
        Canvas
      </button>
    </div>

    <div class="flex items-center gap-2">
      <div class="w-1.5 h-1.5 rounded-full {wsStore.connected ? 'bg-signal animate-pulse' : 'bg-text-dim'}"></div>
      <span class="text-[11px] text-text-dim">
        {wsStore.connected ? 'live' : 'disconnected'}
      </span>
    </div>
  </header>

  <!-- Canvas toolbar -->
  {#if canvasMode}
    <div class="flex items-center gap-2 h-8 px-5 border-b border-border-subtle bg-surface/50 shrink-0">
      <button
        onclick={clearLayout}
        class="text-[10px] text-text-dim hover:text-text transition-colors"
      >
        Clear
      </button>
      <button
        onclick={() => isCanvasAgentOpen = !isCanvasAgentOpen}
        class="text-[10px] transition-colors {isCanvasAgentOpen ? 'text-signal' : 'text-text-dim hover:text-text'}"
      >
        Agent
      </button>
    </div>
  {/if}

  <!-- Main content -->
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <aside class="w-56 border-r border-border-subtle overflow-y-auto shrink-0 flex flex-col">
      <SidebarTabs
        active={sidebarTab}
        onChange={(tab) => {
          sidebarTab = tab;
          if (tab === 'files') clearCommit();
        }}
      />
      {#if sidebarTab === 'files'}
        <CategoryFilter
          functions={fnStore.functions}
          {selectedCategory}
          onSelectCategory={(c) => selectedCategory = c}
        />
        <FileTree
          files={fnStore.files}
          functions={filteredFunctions}
          highlightedIds={gitStore.highlightedFunctionIds}
          onSelectFunction={handleSelectFunction}
        />
      {/if}
      {#if sidebarTab === 'commits'}
        <CommitList
          commits={gitStore.commits}
          selectedHash={gitStore.selectedHash}
          onSelectCommit={(hash) => selectCommit(hash, fnStore.functions)}
        />
      {/if}
    </aside>

    <!-- Main area -->
    <main class="flex-1 overflow-hidden relative flex flex-col">
      {#if sidebarTab === 'commits' && gitStore.commitDiff}
        <DiffView
          diff={gitStore.commitDiff}
          activeFunctionId={fnStore.selectedId}
          functions={fnStore.functions}
          isLoading={gitStore.isLoadingDiff}
        />
      {:else}
        <GraphScopeBar
          scopeMode={scopeStore.scopeMode}
          totalCount={fnStore.functions.length}
          scopedCount={scopedFunctions.length}
          {clearScope}
          functions={fnStore.functions}
          commitHash={gitStore.selectedHash}
        />
        <FunctionGraph
          functions={scopedFunctions}
          edges={scopedEdges}
          canvasLayout={canvasMode ? layoutStore.layout : EMPTY_CANVAS_LAYOUT}
          selectedId={fnStore.selectedId}
          highlightedIds={gitStore.highlightedFunctionIds}
          onSelectFunction={handleSelectFunction}
          onPinNode={canvasMode ? pinNode : undefined}
          {canvasMode}
          {analysisMap}
        />
      {/if}
    </main>

    <!-- Detail panel -->
    {#if isDetailOpen && selectedFunction}
      <DetailPanel
        fn={selectedFunction}
        isOpen={isDetailOpen}
        onClose={handleCloseDetail}
        onAskAgent={handleAskAgent}
        onOpenEditor={handleOpenEditor}
        edges={fnStore.edges}
        allFunctions={fnStore.functions}
        onSelectFunction={handleSelectFunction}
        analysisResults={getAnalysesForFunction(selectedFunction.id)}
        activeAnalysisRun={activeAnalysisRunForSelected}
        onTriggerAnalysis={handleTriggerAnalysis}
        onStopAnalysis={stopAnalysis}
        onDebugFunction={handleDebugFunction}
        onDebugCallChain={handleDebugCallChain}
        onFocusFunction={setFocusMode}
      />
    {/if}

    <!-- Canvas agent panel -->
    {#if canvasMode && isCanvasAgentOpen}
      <CanvasAgentPanel
        isOpen={isCanvasAgentOpen}
        onClose={() => isCanvasAgentOpen = false}
        onCommand={applyCommand}
        functions={fnStore.functions}
        edges={fnStore.edges}
        layout={layoutStore.layout}
      />
    {/if}
  </div>

  <!-- Agent modal -->
  {#if isAgentModalOpen && agentContext}
    <AgentModal
      isOpen={isAgentModalOpen}
      onClose={handleCloseAgent}
      context={agentContext}
    />
  {/if}

  <!-- Search palette (Cmd+K) -->
  <SearchPalette
    functions={fnStore.functions}
    isOpen={isSearchOpen}
    onClose={() => isSearchOpen = false}
    onSelect={handleSearchSelect}
  />
</div>

// packages/dashboard/src/components/WorkspaceLayout.tsx
'use client';

import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import type { AgentContext, FunctionCategory, CanvasLayout, AnalysisResult, WsMessage } from '@agent-monitor/types';
import { useFunctions } from '@/hooks/useFunctions';
import { useWebSocket } from '@/hooks/useWebSocket';
import { useGitCommits } from '@/hooks/useGitCommits';
import { useCanvasLayout } from '@/hooks/useCanvasLayout';
import { useAnalysis } from '@/hooks/useAnalysis';
import { useGraphScope } from '@/hooks/useGraphScope';
import { WS_URL } from '@/lib/constants';
import { SidebarTabs } from '@/components/Sidebar/SidebarTabs';
import { FileTree } from '@/components/FileTree/FileTree';
import { CategoryFilter } from '@/components/FileTree/CategoryFilter';
import { FunctionGraph } from '@/components/Graph/FunctionGraph';
import { GraphScopeBar } from '@/components/Graph/GraphScopeBar';
import { CommitList } from '@/components/Commits/CommitList';
import { DiffView } from '@/components/Commits/DiffView';
import { DetailPanel } from '@/components/Detail/DetailPanel';
import { AgentModal } from '@/components/Agent/AgentModal';
import { CanvasAgentPanel } from '@/components/Agent/CanvasAgentPanel';
import { SearchPalette } from '@/components/Search/SearchPalette';
import { openInEditor, launchDebugSession } from '@/lib/api';

const EMPTY_CANVAS_LAYOUT: CanvasLayout = { version: 1, positions: [], groups: [], annotations: [] };

export function WorkspaceLayout() {
  const { functions, files, edges, selectedId, selectFunction, handleMessage: handleFunctionsMessage } = useFunctions();
  const {
    analyses,
    activeRuns,
    handleAnalysisMessage,
    triggerAnalysis,
    stopAnalysis,
    getAnalysesForFunction,
  } = useAnalysis();
  const { connected } = useWebSocket({
    url: WS_URL,
    onMessage: useCallback(
      (msg: WsMessage) => {
        handleFunctionsMessage(msg);
        if (msg.type.startsWith('analysis-')) {
          handleAnalysisMessage(msg);
        }
      },
      [handleFunctionsMessage, handleAnalysisMessage],
    ),
  });
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [isAgentModalOpen, setIsAgentModalOpen] = useState(false);
  const [agentContext, setAgentContext] = useState<AgentContext | null>(null);
  const [sidebarTab, setSidebarTab] = useState<'files' | 'commits'>('files');
  const [selectedCategory, setSelectedCategory] = useState<FunctionCategory | null>(null);
  const [canvasMode, setCanvasMode] = useState(false);
  const [isCanvasAgentOpen, setIsCanvasAgentOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);

  // Cmd+K / Ctrl+K to open search palette
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setIsSearchOpen(true);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  const {
    layout,
    pinNode,
    applyCommand,
    clearLayout,
  } = useCanvasLayout();

  const {
    commits,
    selectedHash,
    commitDiff,
    highlightedFunctionIds,
    selectCommit,
    clearCommit,
    isLoadingDiff,
  } = useGitCommits(functions);

  const {
    scopedFunctions,
    scopedEdges,
    scopeMode,
    setFocusMode,
    setCommitMode,
    setCategoryMode,
    clearScope,
    isScoped,
  } = useGraphScope({ functions, edges });

  // Auto-scope: when highlightedFunctionIds changes (commit selected), enter commit scope
  const prevHighlightedRef = useRef<Set<string>>(highlightedFunctionIds);
  useEffect(() => {
    if (highlightedFunctionIds !== prevHighlightedRef.current) {
      prevHighlightedRef.current = highlightedFunctionIds;
      if (highlightedFunctionIds.size > 0) {
        setCommitMode(highlightedFunctionIds);
      } else {
        clearScope();
      }
    }
  }, [highlightedFunctionIds, setCommitMode, clearScope]);

  // Auto-scope: when category filter changes, enter category scope
  useEffect(() => {
    if (selectedCategory) {
      setCategoryMode(new Set([selectedCategory]));
    } else {
      clearScope();
    }
  }, [selectedCategory, setCategoryMode, clearScope]);

  // Auto-scope: if >300 functions and no scope active, default to recent commit or first 300
  const autoScopeAppliedRef = useRef(false);
  useEffect(() => {
    if (autoScopeAppliedRef.current) return;
    if (functions.length <= 300) return;
    if (isScoped) return;
    // Wait for commits to load before deciding
    if (commits.length > 0 && highlightedFunctionIds.size === 0) {
      // Commits loaded but none selected — auto-select the most recent commit
      selectCommit(commits[0].hash);
      autoScopeAppliedRef.current = true;
    }
  }, [functions.length, isScoped, commits, highlightedFunctionIds.size, selectCommit]);

  const filteredFunctions = useMemo(
    () =>
      selectedCategory
        ? functions.filter((fn) => fn.category === selectedCategory)
        : functions,
    [functions, selectedCategory],
  );

  const selectedFunction = selectedId
    ? functions.find((f) => f.id === selectedId) ?? null
    : null;

  const handleSelectFunction = useCallback(
    (id: string) => {
      selectFunction(id);
      setIsDetailOpen(true);
    },
    [selectFunction],
  );

  const handleCloseDetail = useCallback(() => {
    setIsDetailOpen(false);
  }, []);

  const handleAskAgent = useCallback((ctx: AgentContext) => {
    setAgentContext(ctx);
    setIsAgentModalOpen(true);
  }, []);

  const handleOpenEditor = useCallback(() => {
    if (selectedFunction) {
      openInEditor(selectedFunction.filePath, selectedFunction.line);
    }
  }, [selectedFunction]);

  const handleCloseAgent = useCallback(() => {
    setIsAgentModalOpen(false);
  }, []);

  const scopedIds = useMemo(
    () => new Set(scopedFunctions.map((f) => f.id)),
    [scopedFunctions],
  );

  const analysisMap = useMemo(() => {
    const map = new Map<string, AnalysisResult[]>();
    for (const a of analyses) {
      if (!scopedIds.has(a.functionId)) continue;
      const existing = map.get(a.functionId);
      if (existing) {
        existing.push(a);
      } else {
        map.set(a.functionId, [a]);
      }
    }
    return map;
  }, [analyses, scopedIds]);

  const activeAnalysisRunForSelected = useMemo(
    () =>
      activeRuns.find(
        (r) =>
          (r.status === 'running' || r.status === 'queued') &&
          (selectedId && r.functionIds && r.functionIds.includes(selectedId)),
      ),
    [activeRuns, selectedId],
  );

  const handleTriggerAnalysis = useCallback(
    (functionId: string, taskName?: string) => triggerAnalysis([functionId], taskName),
    [triggerAnalysis],
  );

  const handleDebugFunction = useCallback(
    (opts: { filePath: string; line: number; functionName: string }) => launchDebugSession(opts),
    [],
  );

  const handleSearchSelect = useCallback(
    (functionId: string) => {
      selectFunction(functionId);
      setIsDetailOpen(true);
      setFocusMode(functionId);
      setIsSearchOpen(false);
    },
    [selectFunction, setFocusMode],
  );

  const handleDebugCallChain = useCallback(
    (chain: Array<{ filePath: string; line: number; name: string }>) => {
      if (chain.length === 0) return;
      const primary = chain[0];
      launchDebugSession({
        filePath: primary.filePath,
        line: primary.line,
        functionName: primary.name,
        callChain: chain,
      });
    },
    [],
  );

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-void">
      {/* Top bar */}
      <header className="flex items-center justify-between h-11 px-5 border-b border-border-subtle shrink-0">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="text-signal">
              <circle cx="7" cy="7" r="5" stroke="currentColor" strokeWidth="1.5" />
              <circle cx="7" cy="7" r="2" fill="currentColor" />
            </svg>
            <span className="text-[13px] font-medium tracking-tight text-text">
              vigil
            </span>
          </div>
          <span className="text-text-dim text-[11px]">/</span>
          <span className="text-text-secondary text-[11px]">
            {functions.length} function{functions.length !== 1 ? 's' : ''} tracked
          </span>
          <button
            onClick={() => setCanvasMode((v) => !v)}
            className={`flex items-center gap-1.5 px-2.5 py-1 text-[11px] rounded transition-colors ${
              canvasMode
                ? 'bg-signal/10 text-signal border border-signal/30'
                : 'text-text-dim border border-border-subtle hover:text-text'
            }`}
          >
            Canvas
          </button>
        </div>

        <div className="flex items-center gap-2">
          <div
            className={`w-1.5 h-1.5 rounded-full ${
              connected ? 'bg-signal animate-pulse' : 'bg-text-dim'
            }`}
          />
          <span className="text-[11px] text-text-dim">
            {connected ? 'live' : 'disconnected'}
          </span>
        </div>
      </header>

      {/* Canvas toolbar */}
      {canvasMode && (
        <div className="flex items-center gap-2 h-8 px-5 border-b border-border-subtle bg-surface/50 shrink-0">
          <button
            onClick={clearLayout}
            className="text-[10px] text-text-dim hover:text-text transition-colors"
          >
            Clear
          </button>
          <button
            onClick={() => setIsCanvasAgentOpen((v) => !v)}
            className={`text-[10px] transition-colors ${
              isCanvasAgentOpen ? 'text-signal' : 'text-text-dim hover:text-text'
            }`}
          >
            Agent
          </button>
        </div>
      )}

      {/* Main content */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <aside className="w-56 border-r border-border-subtle overflow-y-auto shrink-0 flex flex-col">
          <SidebarTabs
            active={sidebarTab}
            onChange={(tab) => {
              setSidebarTab(tab);
              if (tab === 'files') clearCommit();
            }}
          />
          {sidebarTab === 'files' && (
            <>
              <CategoryFilter
                functions={functions}
                selectedCategory={selectedCategory}
                onSelectCategory={setSelectedCategory}
              />
              <FileTree
                files={files}
                functions={filteredFunctions}
                highlightedIds={highlightedFunctionIds}
                onSelectFunction={handleSelectFunction}
              />
            </>
          )}
          {sidebarTab === 'commits' && (
            <CommitList
              commits={commits}
              selectedHash={selectedHash}
              onSelectCommit={selectCommit}
            />
          )}
        </aside>

        {/* Main area */}
        <main className="flex-1 overflow-hidden relative flex flex-col">
          {sidebarTab === 'commits' && commitDiff ? (
            <DiffView
              diff={commitDiff}
              activeFunctionId={selectedId}
              functions={functions}
              isLoading={isLoadingDiff}
            />
          ) : (
            <>
              <GraphScopeBar
                scopeMode={scopeMode}
                totalCount={functions.length}
                scopedCount={scopedFunctions.length}
                clearScope={clearScope}
                functions={functions}
                commitHash={selectedHash}
              />
              <FunctionGraph
                functions={scopedFunctions}
                edges={scopedEdges}
                canvasLayout={canvasMode ? layout : EMPTY_CANVAS_LAYOUT}
                selectedId={selectedId}
                highlightedIds={highlightedFunctionIds}
                onSelectFunction={handleSelectFunction}
                onPinNode={canvasMode ? pinNode : undefined}
                canvasMode={canvasMode}
                analysisMap={analysisMap}
              />
            </>
          )}
        </main>

        {/* Detail panel */}
        {isDetailOpen && selectedFunction && (
          <DetailPanel
            fn={selectedFunction}
            isOpen={isDetailOpen}
            onClose={handleCloseDetail}
            onAskAgent={handleAskAgent}
            onOpenEditor={handleOpenEditor}
            edges={edges}
            allFunctions={functions}
            onSelectFunction={handleSelectFunction}
            analysisResults={getAnalysesForFunction(selectedFunction.id)}
            activeAnalysisRun={activeAnalysisRunForSelected}
            onTriggerAnalysis={handleTriggerAnalysis}
            onStopAnalysis={stopAnalysis}
            onDebugFunction={handleDebugFunction}
            onDebugCallChain={handleDebugCallChain}
            onFocusFunction={setFocusMode}
          />
        )}

        {/* Canvas agent panel */}
        {canvasMode && isCanvasAgentOpen && (
          <CanvasAgentPanel
            isOpen={isCanvasAgentOpen}
            onClose={() => setIsCanvasAgentOpen(false)}
            onCommand={applyCommand}
            functions={functions}
            edges={edges}
            layout={layout}
          />
        )}
      </div>

      {/* Agent modal */}
      {isAgentModalOpen && agentContext && (
        <AgentModal
          isOpen={isAgentModalOpen}
          onClose={handleCloseAgent}
          context={agentContext}
        />
      )}

      {/* Search palette (Cmd+K) */}
      <SearchPalette
        functions={functions}
        isOpen={isSearchOpen}
        onClose={() => setIsSearchOpen(false)}
        onSelect={handleSearchSelect}
      />
    </div>
  );
}
